version: "3.1"
services:
    app:
        build: .
        image: name
        restart: always
        env_file:
            - .env
        ports:
            - 3000:3000

    mongo:
        image: mongo
        restart: always
        env_file:
            - .env

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - .env
